### ISSUE TITLE
Login page for doctor

### ISSUE THREAD

**Issue by Anagha-2000** [Anagha-2000/PsychHelp#13]

**Comment by divanshurox** [comment]
Hi, can I work on this I am new to open source. Thanks!

**Comment by Anagha-2000** [comment]
Are you a participant at Student Code-in? And what's your name?

**Comment by divanshurox** [comment]
Hi I am Divanshu Agarwal, but I am not a part of Student Code-in.

**Comment by Anagha-2000** [comment]
Completed the front-end of the login page
