### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by kushal98** [Anagha-2000/PsychHelp#21]
Hey,

Can u please mention setup steps. I tried doing a local setup but its giving some error.
Steps followed by me after cloning repo :

```
npm install
npm start
```

Errors : 
```
./src/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/index.css)
Error: Package exports for 'E:\React\PsychHelp\node_modules\autoprefixer\node_modules\kleur' do not define a valid './colors' target
```

Thanks

**Comment by nehasangeetajha** [comment]
try yarn install and yarn start
it works

**Comment by kushal98** [comment]
Thanks for suggestion @nehasangeetajha but the same issue still exists.

**Comment by gagangaur** [comment]
documentation is still not updated shall I throw a PR correcting docs?

**Comment by Anagha-2000** [comment]
Hi, you have to install npm. so the commands go like this:

npm install
npm start

I tried this myself and it's working.

I have updated the README file. You can go through that.
