### ISSUE TITLE
adding content to the 2 About Us pages for doctor and patient & the FAQs section

### ISSUE THREAD

**Issue by Anagha-2000** [Anagha-2000/PsychHelp#4]
The 'learn more' button on the home page for doctor and patient will lead to the separate About Us pages respectively. The part left to do is styling and content.

**Comment by nehasangeetajha** [comment]
Please assign me this issue

**Comment by Anagha-2000** [comment]
Hey there's been a change in the structure. The About Us page is now changed to two different pages for doctor and patient. If u see the home page there are  two cards namely for doctor and patient.  The 'learn more' button takes u to a another page I.e. the About Us page. I have already created those 2 pages in the AboutUs folder. There's only styling and content left to do. If u want I'll assign you the issue but then u have to work on both the pages.
